apiVersion: v1
kind: ConfigMap
metadata:
  name: kube-rbac-proxy
  namespace: ci-operator-result-aggregation-server
data:
  config-file.yaml: |+
    authorization:
      resourceAttributes:
        apiVersion: v1
        resource: namespace
        subresource: metrics
        namespace: ci-operator-result-aggregation-server
