---
apiVersion: v1
kind: Service
metadata:
  name: ci-operator-result-aggregation-server
  namespace: ci-operator-result-aggregation-server
  annotations:
    service.alpha.openshift.io/serving-cert-secret-name: ci-operator-result-aggregation-server-tls
  labels:
    k8s-app: ci-operator-result-aggregation-server
spec:
  type: ClusterIP
  ports:
  - name: https
    port: 8443
    targetPort: https
  selector:
    k8s-app: ci-operator-result-aggregation-server
  sessionAffinity: None
